### ISSUE TITLE
PlaceLocationType : Embassy missing

### ISSUE THREAD

**Issue by sandrinev** [vivet/GoogleApi#65]
Hello,
I wanted to do a placesTextSearchRequest with the type set to embassy, but it seems like it is missing.
(It is available in the types listed on google maps documentation).

![embassy](https://user-images.githubusercontent.com/28351871/33564770-a162d5de-d91b-11e7-9a40-fd49356d0746.png)
![image](https://user-images.githubusercontent.com/28351871/33564885-f687968a-d91b-11e7-90c9-4d67994280cf.png)

**Comment by vivet** [comment]
Hi 
I will add it

**Comment by vivet** [comment]
Fixed.
Nuget pacakge v3.2.11 published.

**Comment by vivet** [comment]
By the way, you should use SearchPlaceType

**Comment by sandrinev** [comment]
Hi,
Yes you're right, it is the SearchPlaceType I should be using.
Thanks for the help!

There's still a little issue with the results, which use PlaceLocationType as Type and where the embassy type is still missing.

**Comment by vivet** [comment]
hmm
Okay will try to align that as well

**Comment by vivet** [comment]
https://github.com/vivet/GoogleApi/tree/ISSUE_65_2

**Comment by vivet** [comment]
Solved
Nuget package published (https://www.nuget.org/packages/GoogleApi/3.2.12)

**Comment by sandrinev** [comment]
It works fine! Thanks a lot!

**Comment by vivet** [comment]
Please give my repository a star if you like it :-)
